!Command
positional: []
named: []
command:
- plantcv-utils.py
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmpwh923u31/bin/plantcv-utils.py\"\
  , line 5, in <module>\n    import plantcv.utils\n  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/utils/__init__.py\"\
  , line 4, in <module>\n    from plantcv.utils.sample_images import sample_images\n\
  \  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/utils/sample_images.py\"\
  , line 5, in <module>\n    from plantcv.plantcv import fatal_error\n  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/plantcv/__init__.py\"\
  , line 137, in <module>\n    from plantcv.plantcv.print_image import print_image\n\
  \  File \"/tmp/tmpwh923u31/lib/python3.7/site-packages/plantcv/plantcv/print_image.py\"\
  , line 3, in <module>\n    import cv2\nImportError: libGL.so.1: cannot open shared\
  \ object file: No such file or directory\n"
generated_using:
- --help
