Acclimatising the command GRCh37_bench.vcf failed with error
Traceback (most recent call last):
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 313, in commands_from_package
    [exe.name], run_kwargs={"cwd": dir}
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 179, in explore_command
    command = best_cmd(cmd, flags, run_kwargs=run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 101, in best_cmd
    final = execute_cmd(help_cmd, **run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/execution.py", line 36, in execute_cmd
    master, slave = pty.openpty()
  File "/mnt/miniconda3/lib/python3.7/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/mnt/miniconda3/lib/python3.7/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
