!Command
command:
- extract_genes.py
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/extract_genes.py\"\
  , line 37, in <module>\n    record=SeqIO.read(sys.argv[1], \"genbank\", generic_dna)\n\
  \  File \"/usr/local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py\", line 744,\
  \ in read\n    first = next(iterator)\n  File \"/usr/local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py\"\
  , line 687, in _force_alphabet\n    for record in record_iterator:\n  File \"/usr/local/lib/python2.7/site-packages/Bio/GenBank/Scanner.py\"\
  , line 514, in parse_records\n    with as_handle(handle, \"rU\") as handle:\n  File\
  \ \"/usr/local/lib/python2.7/contextlib.py\", line 17, in __enter__\n    return\
  \ self.gen.next()\n  File \"/usr/local/lib/python2.7/site-packages/Bio/File.py\"\
  , line 120, in as_handle\n    with open(handleish, mode, **kwargs) as fp:\nIOError:\
  \ [Errno 2] No such file or directory: '--help'\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/mitofinder:1.4--py27h516909a_0
