!Command
command:
- cravat-filter
- Command
positional:
- !Positional
  optional: false
  position: 0
  name: cravat-filter
  description: ''
named:
- !Flag
  optional: true
  synonyms:
  - -F
  description: ''
  args: !SimpleFlagArg
    name: FILTERNAME
- !Flag
  optional: true
  synonyms:
  - -f
  description: ''
  args: !SimpleFlagArg
    name: FILTERPATH
- !Flag
  optional: true
  synonyms:
  - -d
  description: ''
  args: !SimpleFlagArg
    name: DBPATH
parent:
subcommands: []
usage: []
help_flag: !Flag
  optional: true
  synonyms:
  - -h
  description: ''
  args: !EmptyFlagArg {}
usage_flag:
version_flag:
help_text: "usage: cravat-filter [-h] -d DBPATH [-f FILTERPATH] [-F FILTERNAME]\n\
  \                     [--filterstring FILTERSTRING] [-l {variant,gene}]\n      \
  \               [-s SAVEFILTERNAME]\n                     {uidpipe,count,rows,pipe,save,list}\n\
  cravat-filter: error: argument command: invalid choice: 'Command' (choose from 'uidpipe',\
  \ 'count', 'rows', 'pipe', 'save', 'list')\nTask exception was never retrieved\n\
  future: <Task finished name='Task-2' coro=<CravatFilter.run() done, defined at /usr/local/lib/python3.9/site-packages/cravat/cravat_filter.py:206>\
  \ exception=SystemExit(2)>\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 1851, in parse_known_args\n    namespace, args = self._parse_known_args(args,\
  \ namespace)\n  File \"/usr/local/lib/python3.9/argparse.py\", line 2042, in _parse_known_args\n\
  \    positionals_end_index = consume_positionals(start_index)\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 2019, in consume_positionals\n    take_action(action, args)\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 1912, in take_action\n    argument_values = self._get_values(action, argument_strings)\n\
  \  File \"/usr/local/lib/python3.9/argparse.py\", line 2444, in _get_values\n  \
  \  self._check_value(action, value)\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 2500, in _check_value\n    raise ArgumentError(action, msg % args)\nargparse.ArgumentError:\
  \ argument command: invalid choice: 'Command' (choose from 'uidpipe', 'count', 'rows',\
  \ 'pipe', 'save', 'list')\n\nDuring handling of the above exception, another exception\
  \ occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/nest_asyncio.py\"\
  , line 92, in run_until_complete\n    self._run_once()\n  File \"/usr/local/lib/python3.9/site-packages/nest_asyncio.py\"\
  , line 130, in _run_once\n    handle._run()\n  File \"/usr/local/lib/python3.9/site-packages/nest_asyncio.py\"\
  , line 199, in run\n    ctx.run(self._callback, *self._args)\n  File \"/usr/local/lib/python3.9/site-packages/nest_asyncio.py\"\
  , line 157, in step\n    step_orig(task, exc)\n  File \"/usr/local/lib/python3.9/asyncio/tasks.py\"\
  , line 256, in __step\n    result = coro.send(None)\n  File \"/usr/local/lib/python3.9/site-packages/cravat/cravat_filter.py\"\
  , line 208, in run\n    self.parse_args(args)\n  File \"/usr/local/lib/python3.9/site-packages/cravat/cravat_filter.py\"\
  , line 281, in parse_args\n    parsed_args = parser.parse_args(args)\n  File \"\
  /usr/local/lib/python3.9/argparse.py\", line 1818, in parse_args\n    args, argv\
  \ = self.parse_known_args(args, namespace)\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 1854, in parse_known_args\n    self.error(str(err))\n  File \"/usr/local/lib/python3.9/argparse.py\"\
  , line 2575, in error\n    self.exit(2, _('%(prog)s: error: %(message)s\\n') % args)\n\
  \  File \"/usr/local/lib/python3.9/argparse.py\", line 2562, in exit\n    _sys.exit(status)\n\
  SystemExit: 2\n"
generated_using:
- --help
docker_image: quay.io/biocontainers/open-cravat:2.2.2--pyh3252c3a_0
