!Command
command:
- platypus
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/platypus\"\
  , line 12, in <module>\n    from platypus.commands import (compare as platy_compare,\n\
  \  File \"/usr/local/lib/python2.7/site-packages/platypus/commands.py\", line 14,\
  \ in <module>\n    from skbio.util import create_dir\n  File \"/usr/local/lib/python2.7/site-packages/skbio/__init__.py\"\
  , line 15, in <module>\n    import skbio.io\n  File \"/usr/local/lib/python2.7/site-packages/skbio/io/__init__.py\"\
  , line 309, in <module>\n    import_module('skbio.io.clustal')\n  File \"/usr/local/lib/python2.7/importlib/__init__.py\"\
  , line 37, in import_module\n    __import__(name)\n  File \"/usr/local/lib/python2.7/site-packages/skbio/io/clustal.py\"\
  , line 123, in <module>\n    from skbio.alignment import Alignment\n  File \"/usr/local/lib/python2.7/site-packages/skbio/alignment/__init__.py\"\
  , line 230, in <module>\n    from ._alignment import Alignment, SequenceCollection,\
  \ StockholmAlignment\n  File \"/usr/local/lib/python2.7/site-packages/skbio/alignment/_alignment.py\"\
  , line 21, in <module>\n    from skbio.stats.distance import DistanceMatrix\n  File\
  \ \"/usr/local/lib/python2.7/site-packages/skbio/stats/distance/__init__.py\", line\
  \ 193, in <module>\n    from ._base import (DissimilarityMatrixError, DistanceMatrixError,\n\
  \  File \"/usr/local/lib/python2.7/site-packages/skbio/stats/distance/_base.py\"\
  , line 16, in <module>\n    import matplotlib.pyplot as plt\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py\"\
  , line 115, in <module>\n    _backend_mod, new_figure_manager, draw_if_interactive,\
  \ _show = pylab_setup()\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py\"\
  , line 63, in pylab_setup\n    [backend_name], 0)\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py\"\
  , line 4, in <module>\n    from . import tkagg  # Paint image to Tk photo blitter\
  \ extension.\n  File \"/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py\"\
  , line 5, in <module>\n    from six.moves import tkinter as Tk\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 203, in load_module\n    mod = mod._resolve()\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 115, in _resolve\n    return _import_module(self.mod)\n  File \"/usr/local/lib/python2.7/site-packages/six.py\"\
  , line 82, in _import_module\n    __import__(name)\n  File \"/usr/local/lib/python2.7/lib-tk/Tkinter.py\"\
  , line 39, in <module>\n    import _tkinter # If this fails your Python may not\
  \ be configured for Tk\nImportError: libX11.so.6: cannot open shared object file:\
  \ No such file or directory\n"
generated_using:
- --help
