Acclimatising the command exclude-uid-lists failed with error
Traceback (most recent call last):
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/execution.py", line 45, in execute_cmd
    stdout, stderr = process.communicate(timeout=timeout)
  File "/mnt/miniconda3/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/mnt/miniconda3/lib/python3.7/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/mnt/miniconda3/lib/python3.7/subprocess.py", line 1011, in _check_timeout
    stderr=b''.join(stderr_seq) if stderr_seq else None)
subprocess.TimeoutExpired: Command '['exclude-uid-lists', 'OPTION', '-h']' timed out after 5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/BiocondaCli/bioconda_cli/main.py", line 313, in commands_from_package
    [exe.name], run_kwargs={"cwd": dir}
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 203, in explore_command
    try_subcommand_flags=try_subcommand_flags,
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 179, in explore_command
    command = best_cmd(cmd, flags, run_kwargs=run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/__init__.py", line 101, in best_cmd
    final = execute_cmd(help_cmd, **run_kwargs)
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/execution.py", line 51, in execute_cmd
    sig=signal.SIGKILL if sys.platform == "linux" else None,
  File "/mnt/miniconda3/lib/python3.7/site-packages/acclimatise/execution.py", line 29, in kill_proc_tree
    p.send_signal(sig)
  File "/mnt/miniconda3/lib/python3.7/site-packages/psutil/__init__.py", line 291, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=2101)
