!Command
command:
- pvacseq-ui
positional: []
named: []
parent:
subcommands: []
usage: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/usr/local/bin/pvacseq-ui\"\
  , line 10, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.6/site-packages/pvacseq/server/app.py\"\
  , line 25, in main\n    app.add_api('swagger.yaml', arguments={'title': 'API to\
  \ support pVacSeq user interface for generating reports on pipeline results'})\n\
  \  File \"/usr/local/lib/python3.6/site-packages/connexion/apps/flask_app.py\",\
  \ line 54, in add_api\n    api = super(FlaskApp, self).add_api(specification, **kwargs)\n\
  \  File \"/usr/local/lib/python3.6/site-packages/connexion/apps/abstract.py\", line\
  \ 162, in add_api\n    options=api_options.as_dict())\n  File \"/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py\"\
  , line 97, in __init__\n    self.specification = self.load_spec_from_file(arguments,\
  \ specification_path)\n  File \"/usr/local/lib/python3.6/site-packages/connexion/apis/abstract.py\"\
  , line 288, in load_spec_from_file\n    with specification.open(mode='rb') as swagger_yaml:\n\
  \  File \"/usr/local/lib/python3.6/pathlib.py\", line 1183, in open\n    opener=self._opener)\n\
  \  File \"/usr/local/lib/python3.6/pathlib.py\", line 1037, in _opener\n    return\
  \ self._accessor.open(self, flags, mode)\n  File \"/usr/local/lib/python3.6/pathlib.py\"\
  , line 387, in wrapped\n    return strfunc(str(pathobj), *args)\nFileNotFoundError:\
  \ [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/pvacseq/server/swagger/swagger.yaml'\n"
generated_using:
- --help
