!Command
positional: []
named: []
command:
- rdfs2dot
parent:
subcommands: []
help_flag:
usage_flag:
version_flag:
help_text: "Traceback (most recent call last):\n  File \"/tmp/tmp4kfh13z6/bin/rdfs2dot\"\
  , line 11, in <module>\n    load_entry_point('rdflib==4.2.2', 'console_scripts',\
  \ 'rdfs2dot')()\n  File \"/tmp/tmp4kfh13z6/lib/python3.4/site-packages/rdflib/tools/rdfs2dot.py\"\
  , line 109, in main\n    rdflib.extras.cmdlineutils.main(rdfs2dot, _help)\n  File\
  \ \"/tmp/tmp4kfh13z6/lib/python3.4/site-packages/rdflib/extras/cmdlineutils.py\"\
  , line 27, in main\n    args, files = getopt.getopt(sys.argv[1:], \"hf:o:\" + options)\n\
  \  File \"/tmp/tmp4kfh13z6/lib/python3.4/getopt.py\", line 93, in getopt\n    opts,\
  \ args = do_longs(opts, args[0][2:], longopts, args[1:])\n  File \"/tmp/tmp4kfh13z6/lib/python3.4/getopt.py\"\
  , line 157, in do_longs\n    has_arg, opt = long_has_args(opt, longopts)\n  File\
  \ \"/tmp/tmp4kfh13z6/lib/python3.4/getopt.py\", line 174, in long_has_args\n   \
  \ raise GetoptError(_('option --%s not recognized') % opt, opt)\ngetopt.GetoptError:\
  \ option --help not recognized\n"
generated_using:
- --help
